logging:
  level:
    org:
      jooq: info
      springframework:
        web: info

---
spring:
  graphql:
    schema:
      locations: classpath*:io/github/ermadmi78/kobby/cinema/api/**
    websocket:
      path: /graphql
    graphiql:
      enabled: true
  flyway:
    create-schemas: true
    schemas:
      - cinema
  jooq:
    sql-dialect: h2
