/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kobby.gradle.integration.tests

import io.kotest.core.spec.style.AnnotationSpec
import io.kotest.matchers.shouldBe

class LibraryTest : AnnotationSpec() {
    @Test
    fun testSomeLibraryMethod() {
        val classUnderTest = Library()
        classUnderTest.someLibraryMethod() shouldBe true
    }
}
